author: Jason Shipman
category: Other
dependencies:
- base >=4.8 && <4.11
- logging-effect >= 1.1.0 && <1.3
- wl-pprint-text >=1.1.0.4 && <1.2
description: Handy logging handler combinators.
executables:
  route-handler:
    dependencies:
    - logging-effect-extra-handler
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: route-handler.hs
    source-dirs: executable
  route-handler-with-iso8601:
    dependencies:
    - logging-effect-extra-handler
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: route-handler-with-iso8601.hs
    source-dirs: executable
  iso8601-handler:
    dependencies:
    - logging-effect-extra-handler
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: iso8601-handler.hs
    source-dirs: executable
  iso8601plus-handler:
    dependencies:
    - logging-effect-extra-handler
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: iso8601plus-handler.hs
    source-dirs: executable
  rfc822-handler:
    dependencies:
    - logging-effect-extra-handler
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: rfc822-handler.hs
    source-dirs: executable
extra-source-files:
- CHANGELOG.md
- LICENSE.md
- package.yaml
- README.md
ghc-options: -Wall
github: jship/logging-effect-extra
library:
  dependencies:
  - exceptions >= 0.8.0.2 && <0.9
  - time >=1.5 && <1.9
  source-dirs: library
license: MIT
maintainer: Jason Shipman
name: logging-effect-extra-handler
synopsis: Handy logging handler combinators
version: '1.1.0'
