author: Jason Shipman
category: Other
dependencies:
- base >=4.8 && <4.11
- logging-effect >= 1.1.0 && <1.3
- wl-pprint-text >=1.1.0.4 && <1.2
description: TH splices to augment log messages with file info.
executables:
  log-file:
    dependencies:
    - logging-effect-extra-file
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: log-file.hs
    source-dirs: executable
  log-file-and-severity:
    dependencies:
    - logging-effect-extra-file
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: log-file-and-severity.hs
    source-dirs: executable
extra-source-files:
- CHANGELOG.md
- LICENSE.md
- package.yaml
- README.md
ghc-options: -Wall
github: jship/logging-effect-extra
library:
  dependencies:
  - template-haskell
  source-dirs: library
license: MIT
maintainer: Jason Shipman
name: logging-effect-extra-file
synopsis: TH splices to augment log messages with file info
version: '1.0.0'
