author: Jason Shipman
category: Other
dependencies:
- base >=4.8 && <4.12
description: Supplemental packages for `logging-effect`.
executables:
  log-extra:
    dependencies:
    - logging-effect-extra
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: log-extra.hs
    source-dirs: executable
extra-source-files:
- CHANGELOG.md
- LICENSE.md
- package.yaml
- README.md
ghc-options: -Wall
github: jship/logging-effect-extra
library:
  dependencies:
  - logging-effect >= 1.1.0 && <1.4
  - logging-effect-extra-file >= 1.1.0 && <1.2.0
  - logging-effect-extra-handler >= 1.1.2 && <1.2.0
  - prettyprinter == 1.2.*
  source-dirs: library
license: MIT
maintainer: Jason Shipman
name: logging-effect-extra
synopsis: Supplemental packages for `logging-effect`.
version: '1.2.2'
